# Generated by Django 5.1.1 on 2024-10-05 21:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('envios_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Rastreos',
            new_name='Rastreo',
        ),
    ]
