# Generated by Django 5.1.1 on 2024-10-21 21:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('envios_app', '0003_rename_transportista_asignacionvehiculotransportista_id_transportista_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Facturacion_detalle',
            new_name='FacturacionDetalle',
        ),
    ]
