# Generated by Django 5.1.1 on 2024-10-23 21:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('envios_app', '0004_rename_facturacion_detalle_facturaciondetalle'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transportista',
            name='dpi_transportista',
            field=models.CharField(max_length=15),
        ),
        migrations.AlterField(
            model_name='transportista',
            name='licencia_transportista',
            field=models.CharField(max_length=15),
        ),
        migrations.AlterField(
            model_name='transportista',
            name='telefono_transportista',
            field=models.CharField(max_length=15),
        ),
    ]
