# Generated by Django 5.1.1 on 2025-03-17 01:03

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AsignacionVehiculoTransportista',
            fields=[
                ('id_asignacion', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('fecha_asignacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_fin_asignacion', models.DateTimeField(blank=True, null=True)),
                ('activo', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Vehiculo',
            fields=[
                ('id_vehiculo', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('matricula_vehiculo', models.CharField(max_length=20)),
                ('marca_vehiculo', models.CharField(max_length=40)),
                ('modelo_vehiculo', models.CharField(max_length=40)),
                ('activo', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id_cliente', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=30)),
                ('telefono', models.CharField(max_length=20)),
            ],
            options={
                'indexes': [models.Index(fields=['telefono'], name='envios_app__telefon_9ca72f_idx')],
            },
        ),
        migrations.CreateModel(
            name='Envio',
            fields=[
                ('id_envio', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('estado_envio', models.CharField(choices=[('pendiente', 'Pendiente'), ('en_transito', 'En tránsito'), ('entregado', 'Entregado'), ('cancelado', 'Cancelado')], default='pendiente', max_length=15)),
                ('codigo_rastreo', models.CharField(editable=False, max_length=36, unique=True)),
                ('id_asignacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='asignacion', to='envios_app.asignacionvehiculotransportista')),
            ],
        ),
        migrations.CreateModel(
            name='Facturacion',
            fields=[
                ('id_factura', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('id_cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='envios_app.cliente')),
            ],
        ),
        migrations.CreateModel(
            name='FacturacionDetalle',
            fields=[
                ('id_factura_detalle', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('monto_total', models.DecimalField(decimal_places=2, max_digits=10)),
                ('fecha_facturacion', models.DateTimeField(auto_now_add=True)),
                ('metodo_pago', models.CharField(choices=[('efectivo', 'Efectivo'), ('tarjeta', 'Tarjeta'), ('contra entrega', 'Contra Entrega')], max_length=50)),
                ('id_factura', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detalles', to='envios_app.facturacion')),
            ],
        ),
        migrations.CreateModel(
            name='Paquete',
            fields=[
                ('id_paquete', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('descripcion_paquete', models.CharField(max_length=255)),
                ('peso', models.DecimalField(decimal_places=2, max_digits=10)),
                ('dimensiones', models.CharField(max_length=100)),
                ('valor_declarado', models.DecimalField(decimal_places=2, max_digits=12)),
                ('asignado', models.BooleanField(default=False)),
                ('id_envio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='paquetes', to='envios_app.envio')),
            ],
        ),
        migrations.CreateModel(
            name='Rastreo',
            fields=[
                ('id_rastreo', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('ubicacion_actual', models.CharField(max_length=255)),
                ('fecha_hora', models.DateTimeField(auto_now_add=True)),
                ('estado_paquete', models.CharField(choices=[('en_transito', 'En tránsito'), ('en_almacen', 'En almacén'), ('entregado', 'Entregado'), ('demorado', 'Demorado'), ('cancelado', 'Cancelado')], default='en_transito', max_length=15)),
                ('observaciones', models.TextField(blank=True, null=True)),
                ('id_envio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rastreos', to='envios_app.envio')),
            ],
        ),
        migrations.CreateModel(
            name='Transportista',
            fields=[
                ('id_transportista', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('nombre_transportista', models.CharField(max_length=40)),
                ('apellido_transportista', models.CharField(max_length=40)),
                ('dpi_transportista', models.CharField(max_length=15)),
                ('licencia_transportista', models.CharField(max_length=15)),
                ('correo_transportista', models.EmailField(max_length=100)),
                ('telefono_transportista', models.CharField(max_length=15)),
                ('activo', models.BooleanField(default=True)),
            ],
            options={
                'indexes': [models.Index(fields=['telefono_transportista'], name='envios_app__telefon_dcabf0_idx'), models.Index(fields=['dpi_transportista'], name='envios_app__dpi_tra_fae6c2_idx')],
            },
        ),
        migrations.AddField(
            model_name='asignacionvehiculotransportista',
            name='id_transportista',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transportista', to='envios_app.transportista'),
        ),
        migrations.CreateModel(
            name='Ubicacion',
            fields=[
                ('id_ubicacion', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('ciudad', models.CharField(max_length=100)),
                ('calle', models.CharField(max_length=150)),
                ('codigo_postal', models.CharField(max_length=10)),
                ('coordenadas_geograficas', models.CharField(max_length=255)),
                ('referencias', models.TextField()),
                ('id_cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cliente', to='envios_app.cliente')),
            ],
        ),
        migrations.AddField(
            model_name='envio',
            name='id_ubicacion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ubicacion', to='envios_app.ubicacion'),
        ),
        migrations.AddField(
            model_name='asignacionvehiculotransportista',
            name='id_vehiculo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vehiculo', to='envios_app.vehiculo'),
        ),
    ]
