# Generated by Django 5.1.1 on 2024-10-25 00:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('envios_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='asignacionvehiculotransportista',
            name='activo',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='transportista',
            name='activo',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='vehiculo',
            name='activo',
            field=models.BooleanField(default=True),
        ),
    ]
