# Generated by Django 5.1.1 on 2024-10-26 01:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('envios_app', '0003_paquete_asignado'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cliente',
            name='destinatario',
        ),
        migrations.RemoveField(
            model_name='cliente',
            name='telefono_destinatario',
        ),
        migrations.RenameField(
            model_name='cliente',
            old_name='remitente',
            new_name='nombre',
        ),
        migrations.RenameField(
            model_name='cliente',
            old_name='telefono_remitente',
            new_name='telefono',
        ),
    ]
