# Generated by Django 5.1.1 on 2024-10-26 02:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('envios_app', '0004_auto_20241025_1946'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='cliente',
            name='envios_app__telefon_cd6fc4_idx',
        ),
        migrations.RemoveIndex(
            model_name='cliente',
            name='envios_app__telefon_cc86a3_idx',
        ),
        migrations.AddIndex(
            model_name='cliente',
            index=models.Index(fields=['telefono'], name='envios_app__telefon_9ca72f_idx'),
        ),
    ]
