# Generated by Django 5.1.1 on 2025-03-17 00:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('envios_app', '0002_rename_rastreos_rastreo'),
        ('envios_app', '0005_remove_cliente_envios_app__telefon_cd6fc4_idx_and_more'),
    ]

    operations = [
    ]
